- name: Install Prometheus
  apt:
    name: prometheus
    state: latest

- name: Start Prometheus Service
  service:
    name: prometheus
    state: started

- name: Start Prometheus on Boot
  shell: systemctl enable prometheus
