- name: Install HTTPS-Transport
  apt:
    name: apt-transport-https
    state: present

- name: Install GPG Keys
  shell:  wget -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add -

- name: Add Grafana to Repository
  shell: echo "deb https://packages.grafana.com/oss/deb stable main" | sudo tee -a /etc/apt/sources.list.d/grafana.list

- name: Install Grafana
  apt:
    name: grafana
    state: present
    update_cache: yes


- name: Restart Daemon
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Start Grafana-Server
  service:
    name: grafana-server
    state: started

- name: Start Grafana-Server on Boot
  shell: systemctl enable grafana-server.service
